filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    json.keys_under_root: true
    json.add_error_key: true
    processors:
      - add_docker_metadata: ~

processors:
  - drop_event:
      when:
        not:
          equals:
            container.name: "todo-app-backend-1"
  - decode_json_fields:
      fields: ["log"]
      target: "app"
      overwrite_keys: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "app-logs-%{+yyyy.MM.dd}"

setup.template.name: "app-logs"
setup.template.pattern: "app-logs-*"

setup.kibana:
  host: "http://kibana:5601"